### ISSUE TITLE
How do we want to handle roles on archives ingest?

### ISSUE THREAD

**Issue by thisismattmiller** [nypl-registry/ingest-archives#1]
Right now it sets origination role and anything else is contributor. We can check for "recipient" and other archives roles if we add them here:
https://github.com/nypl-registry/ingest-archives/blob/master/lib/utils.js#L109

**Comment by saverkamp** [comment]
Maybe @alexduryee (@alexanderduryee) can give us a full list of archives roles?

**Comment by alexduryee** [comment]
Collection-level roles: https://gist.github.com/alexduryee/206a99dee59500b6766cdc334a324239
Component-level roles: https://gist.github.com/alexduryee/eab4d850f48ea84d67ac52e907d74deb

**Comment by saverkamp** [comment]
@saverkamp to create archives roles mapping based on Alex's lists (use https://github.com/nypl-registry/utils-lexicon/blob/master/lib/maps/catalog_roles.js as a template). (Map origination to both contributor and creator)

@thisismattmiller to add to serialization and ingest.

**Comment by thisismattmiller** [comment]
I needed to have the map for the existing two roles, so I made the mapping file, new archives roles should be added to this:
https://github.com/nypl-registry/utils-lexicon/blob/master/lib/maps/archives_roles.js

**Comment by saverkamp** [comment]
Mapping updated.
